URL_SERVICE = "https://cnt-09bbfc7f-f042-48fc-a850-e2d7248c7de5.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
DATABASE_PATH = "/api/db/resources/product_model.csv"
KITS_PATH = "/api/v1/kits"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
